### PR TITLE
Update Gradle wrapper to 4.10.3

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates Gradle wrapper to `4.10.3`. It also adds a `.gitignore` files, so build output won't show up in version control status.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Updated to latest version `4.0.1` and rebased.

**Comment by friederbluemle** [comment]
Rebased again, and updated to latest version `4.1`.

**Comment by friederbluemle** [comment]
Updated to latest stable Gradle wrapper `4.2.1`

**Comment by friederbluemle** [comment]
Gradle `4.8.1` is now available. I amended my commit and rebased this PR.

**Comment by psommerfeld** [comment]
Can you please upgrade to 4.10.2?

**Comment by friederbluemle** [comment]
@psommerfeld Sure, thanks for the reminder!

**Comment by psommerfeld** [comment]
You're welcome!
Do you know what would cause this error?
d/data/incoming/tools/android/dex2jar-2.x/dex-tools/build/generated-sources/bin$ ./d2j-dex2jar.sh
Error: Could not find or load main class com.googlecode.dex2jar.tools.Dex2jarCmd
Caused by: java.lang.ClassNotFoundException: com.googlecode.dex2jar.tools.Dex2jarCmd

**Comment by friederbluemle** [comment]
Yes, it means a required Java class file was not found on the classpath. You likely don't have the files in the expected locations relative to the working directory.

Can you try to follow these steps:

1. In the root directory run: `./gradlew distZip`
1. `cd dex-tools/build/distributions`
1. Unzip the file `dex-tools-2.1-SNAPSHOT.zip` (file size should be ~5 MB)
1. Run `d2j-dex2jar.sh`

**Comment by friederbluemle** [comment]
Updated to `4.10.3`.

**Comment by friederbluemle** [comment]
Rebased onto latest default branch.

**Comment by pxb1988** [comment]
i have upgrade gradle to 6.9.1, thanks !

**Pull request closed without merging**
